// <auto-generated />
using System;
using FormsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(FormsDbContext))]
    partial class FormsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "accessibility", new[] { "public", "restricted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role", new[] { "user", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "state", new[] { "active", "blocked" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormsAPI.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("comments_pkey");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("FormsAPI.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("image_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("title");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("forms_pkey");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("FormsAPI.FormAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("form_answers_pkey");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("form_answers", (string)null);
                });

            modelBuilder.Entity("FormsAPI.FormQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("DisplayState")
                        .HasColumnType("boolean")
                        .HasColumnName("display_state");

                    b.Property<int?>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int?>("QuestionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("question_type_id");

                    b.HasKey("Id")
                        .HasName("form_questions_pkey");

                    b.HasIndex("FormId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("form_questions", (string)null);
                });

            modelBuilder.Entity("FormsAPI.FormQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("integer")
                        .HasColumnName("answer_id");

                    b.Property<int?>("FormQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("form_question_id");

                    b.HasKey("Id")
                        .HasName("form_question_answers_pkey");

                    b.HasIndex("AnswerId");

                    b.HasIndex("FormQuestionId");

                    b.ToTable("form_question_answers", (string)null);
                });

            modelBuilder.Entity("FormsAPI.FormTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('fromtags_id_seq'::regclass)");

                    b.Property<int?>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("fromtags_pkey");

                    b.HasIndex("FormId");

                    b.HasIndex("TagId");

                    b.ToTable("form_tags", (string)null);
                });

            modelBuilder.Entity("FormsAPI.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("likes_pkey");

                    b.HasIndex("FormId");

                    b.HasIndex(new[] { "UserId", "FormId" }, "likes_user_id_form_id_key")
                        .IsUnique();

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("FormsAPI.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("question_types_pkey");

                    b.ToTable("question_types", (string)null);
                });

            modelBuilder.Entity("FormsAPI.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("FormsAPI.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("topics_pkey");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("FormsAPI.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_idx")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FormsAPI.Comment", b =>
                {
                    b.HasOne("FormsAPI.Form", "Form")
                        .WithMany("Comments")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comments_form_id_fkey");

                    b.HasOne("FormsAPI.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comments_user_id_fkey");

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsAPI.Form", b =>
                {
                    b.HasOne("FormsAPI.Topic", "Topic")
                        .WithMany("Forms")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("forms_topic_id_fkey");

                    b.HasOne("FormsAPI.User", "User")
                        .WithMany("Forms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("forms_user_id_fkey");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsAPI.FormAnswer", b =>
                {
                    b.HasOne("FormsAPI.Form", "Form")
                        .WithMany("FormAnswers")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("form_answers_form_id_fkey");

                    b.HasOne("FormsAPI.User", "User")
                        .WithMany("FormAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("form_answers_user_id_fkey");

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsAPI.FormQuestion", b =>
                {
                    b.HasOne("FormsAPI.Form", "Form")
                        .WithMany("FormQuestions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("form_questions_form_id_fkey");

                    b.HasOne("FormsAPI.QuestionType", "QuestionType")
                        .WithMany("FormQuestions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("form_questions_question_type_id_fkey");

                    b.Navigation("Form");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("FormsAPI.FormQuestionAnswer", b =>
                {
                    b.HasOne("FormsAPI.FormAnswer", "AnswerNavigation")
                        .WithMany("FormQuestionAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("form_question_answers_answer_id_fkey");

                    b.HasOne("FormsAPI.FormQuestion", "FormQuestion")
                        .WithMany("FormQuestionAnswers")
                        .HasForeignKey("FormQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("form_question_answers_form_question_id_fkey");

                    b.Navigation("AnswerNavigation");

                    b.Navigation("FormQuestion");
                });

            modelBuilder.Entity("FormsAPI.FormTag", b =>
                {
                    b.HasOne("FormsAPI.Form", "Form")
                        .WithMany("FormTags")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fromtags_form_id_fkey");

                    b.HasOne("FormsAPI.Tag", "Tag")
                        .WithMany("FormTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fromtags_tag_id_fkey");

                    b.Navigation("Form");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FormsAPI.Like", b =>
                {
                    b.HasOne("FormsAPI.Form", "Form")
                        .WithMany("Likes")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("likes_form_id_fkey");

                    b.HasOne("FormsAPI.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("likes_user_id_fkey");

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsAPI.Form", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FormAnswers");

                    b.Navigation("FormQuestions");

                    b.Navigation("FormTags");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("FormsAPI.FormAnswer", b =>
                {
                    b.Navigation("FormQuestionAnswers");
                });

            modelBuilder.Entity("FormsAPI.FormQuestion", b =>
                {
                    b.Navigation("FormQuestionAnswers");
                });

            modelBuilder.Entity("FormsAPI.QuestionType", b =>
                {
                    b.Navigation("FormQuestions");
                });

            modelBuilder.Entity("FormsAPI.Tag", b =>
                {
                    b.Navigation("FormTags");
                });

            modelBuilder.Entity("FormsAPI.Topic", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("FormsAPI.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FormAnswers");

                    b.Navigation("Forms");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
